//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ItDemand.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ItDemand.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string Architecture_Board_Decision {
            get {
                return ResourceManager.GetString("Architecture Board Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string Architecture_Board_Process {
            get {
                return ResourceManager.GetString("Architecture Board Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string CAB_Decision {
            get {
                return ResourceManager.GetString("CAB Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string CAB_Process {
            get {
                return ResourceManager.GetString("CAB Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;All Demand that requirees additional scrutiny will go through the Demand Committee. The demand Committee will either approve the Demand to Proceed Locally, Proceed as a Fast Track project or to Proceed as a Large Project. Alternativly the demand Committee may request that the Demand return for a second review after additional information or decisions are available.&lt;/p&gt;
        ///&lt;p&gt;Demand Committee - Core Members:&lt;/p&gt;
        ///&lt;ul&gt;
        ///	&lt;li&gt;PMO (Chair)&lt;/li&gt;
        ///	&lt;li&gt;Security&lt;/li&gt;
        ///	&lt;li&gt;Architecture &amp;amp; Applications&lt;/li&gt;
        ///	&lt;l [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DR_Gate_1_Decision {
            get {
                return ResourceManager.GetString("DR Gate 1 Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The PMO Team will review all Demand and categorise it to Proceed Locally or to go to the Demand Committee for addiitonal Scutiny.&lt;/p&gt;
        ///&lt;p&gt;The PMO Team will make this categorisation with input from Subject Matter Experts and the Demand Raiser.&lt;/p&gt;.
        /// </summary>
        internal static string DR_Gate_1_Process {
            get {
                return ResourceManager.GetString("DR Gate 1 Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string DR_Gate_2_Decision {
            get {
                return ResourceManager.GetString("DR Gate 2 Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string DR_Gate_2_Process {
            get {
                return ResourceManager.GetString("DR Gate 2 Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string Gate_3_Decision {
            get {
                return ResourceManager.GetString("Gate 3 Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string Gate_3_Process {
            get {
                return ResourceManager.GetString("Gate 3 Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string Gate_4_Decision {
            get {
                return ResourceManager.GetString("Gate 4 Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string Gate_4_Process {
            get {
                return ResourceManager.GetString("Gate 4 Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;strong&gt;Cloud Solution:&lt;/strong&gt;All cloud solutions must have completed the &lt;a href=&quot;https://lindegroup.sharepoint.com/:w:/s/GlobalISDemandOffice/EZ7oRakelMJCgIXMQmpXmSMBkJbb96SkHm2WfJkUIf_jbw&quot;&gt;&lt;strong&gt;Business Service Level Expectations&lt;/strong&gt;&lt;/a&gt; document. This is an audit requirement and will be verified as part of the Project Closure process.&lt;/p&gt;.
        /// </summary>
        internal static string Gate_5_Decision {
            get {
                return ResourceManager.GetString("Gate 5 Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;&lt;strong&gt;Cloud Solution:&lt;/strong&gt;All cloud solutions must have completed the &lt;a href=&quot;https://lindegroup.sharepoint.com/:w:/s/GlobalISDemandOffice/EZ7oRakelMJCgIXMQmpXmSMBkJbb96SkHm2WfJkUIf_jbw&quot;&gt;&lt;strong&gt;Business Service Level Expectations&lt;/strong&gt;&lt;/a&gt; document. This is an audit requirement and will be verified as part of the Project Closure process.&lt;/p&gt;
        ///.
        /// </summary>
        internal static string Gate_5_Process {
            get {
                return ResourceManager.GetString("Gate 5 Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string Gate_6_Decision {
            get {
                return ResourceManager.GetString("Gate 6 Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string Gate_6_Process {
            get {
                return ResourceManager.GetString("Gate 6 Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;At the end of each project, release or iteration the project stakeholders &lt;strong&gt;should&lt;/strong&gt; ascertain whether the project, release or iteration delivered the required results in terms of capabilities and contributions to strategic goals. Outstanding activities required to achieve planned results of the project should be identified and communicated. Lessons learned &lt;strong&gt;should&lt;/strong&gt; be identified and documented for future projects, releases and iterations.&lt;/p&gt;.
        /// </summary>
        internal static string Gate_7_Decision {
            get {
                return ResourceManager.GetString("Gate 7 Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;All demand that is in the status Gate 7 Closeout Checklist can be progressed to the status &lt;strong&gt;Completed&lt;/strong&gt; once the initiative has been completed.&lt;/p&gt;
        ///&lt;ul&gt;
        ///	&lt;li&gt;Regional PMO or the Project Manager (PM) can request Corporate PMO to set any Demand to Complete.&lt;/li&gt;
        ///	&lt;li&gt;A request to Corporate PMO to set the demand to Complete can be via email, Instant Message, or by assigning the closeout to a PMO member and submitting it.&lt;/li&gt;
        ///	&lt;li&gt;No review (SOX, Medical Validation, Data Protection, etc.)  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Gate_7_Process {
            get {
                return ResourceManager.GetString("Gate 7 Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The IT Director is confirming that the Demand is in line with business priorities and that the requested funding and local resources are available.&lt;/p&gt;
        ///&lt;p&gt;Depending on the complexity of the solution or the Demand, an Architecture review and/or Project Charter may be required.&lt;/p&gt;
        ///&lt;p&gt;The Demand Committee will decide on the need for an Architecture Review.&lt;/p&gt;
        ///&lt;p&gt;IT Director decides on whether the Demand is treated as a project or not.&lt;/p&gt;
        ///.
        /// </summary>
        internal static string IT_Head_Approval_Decision {
            get {
                return ResourceManager.GetString("IT Head Approval Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The Demand is assigned to the relevant IT Director for their review and approval.&lt;/p&gt;.
        /// </summary>
        internal static string IT_Head_Approval_Process {
            get {
                return ResourceManager.GetString("IT Head Approval Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The Demand is assigned to the relevant IT Director for their review and approval.&lt;/p&gt;.
        /// </summary>
        internal static string L1_IT_Head_Initial_Approval_Decision {
            get {
                return ResourceManager.GetString("L1 IT Head Initial Approval Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The Demand is assigned to the relevant IT Director for their review and approval.&lt;/p&gt;.
        /// </summary>
        internal static string L1_IT_Head_Initial_Approval_Process {
            get {
                return ResourceManager.GetString("L1 IT Head Initial Approval Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string Security_Planning_Decision {
            get {
                return ResourceManager.GetString("Security Planning Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string Security_Planning_Process {
            get {
                return ResourceManager.GetString("Security Planning Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string Solution_Design_Decision {
            get {
                return ResourceManager.GetString("Solution Design Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;TBD&lt;/p&gt;.
        /// </summary>
        internal static string Solution_Design_Process {
            get {
                return ResourceManager.GetString("Solution Design Process", resourceCulture);
            }
        }
    }
}
